[package]
name = "redis-whiteboard"
version = "0.1.0"
edition = "2021"

[dependencies]
socketioxide-redis = { path = "../../crates/socketioxide-redis", features = [
    "redis",
    "redis-cluster",
    "fred",
] }
socketioxide = { workspace = true, features = ["tracing", "msgpack"] }
axum.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.5.0", features = ["cors", "fs"] }
tower.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
serde.workspace = true
rmpv.workspace = true

[[bin]]
name = "redis"
path = "src/redis.rs"

[[bin]]
name = "redis-cluster"
path = "src/redis_cluster.rs"

[[bin]]
name = "fred"
path = "src/fred.rs"
