contact_links:
  - name: ğŸ™ Q&A (GitHub Discussions)
    url: https://github.com/totodore/socketioxide/discussions/categories/q-a
    about: Q&A all around socketioxide usage
  - name: ğŸ’¬ Tokio Discord
    url: https://discord.gg/tokio
    about: Community chat for Tokio (socketioxide channel is under libs)